### ISSUE TITLE
Research Joke APIs

### ISSUE THREAD

**Issue by 4LineTime** [4LineTime/Jokester#1]
Create a list of Joke APIS we want to pull from.
Make a shortlist of 3

Current list is
1. Reddit Joke Subreddits
2. Tumbler Text
3. Chuck Norris Joke API

Add more here.

**Comment by DarrenIsaacson** [comment]
Free Joke Api Websites:

Jokes
1. Icanhazdadjoke (https://icanhazdadjoke.com/)
2. JokeApi (https://sv443.net/jokeapi/v2)
3. Joke one (https://jokes.one/)
4. Yo mama Jokes (https://yomomma.info/)

Picture api
1. Meme generator photos (https://api.imgflip.com/)

Sound api
1. FreeSound (https://freesound.org/docs/api/)
